# Change these first
owner: remgi # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: CRM CIVIX
    url: https://crm.civix.mx
  - name: ADMIN CIVIX
    url: https://admin.civix.mx
  - name: Analisis CIVIX
    url: https://analisis.civix.mx
  - name: Sitio CIC
    url: https://cic.mx
  - name: Libres de Extorsion
    url: https://libresdeextorsion.mx
  - name: DONA CIC
    url: https://dona.cic.mx
  - name: APOYA CIC
    url: https://apoya.cic.mx
  - name: Sitio CIVIX
    url: https://civix.mx/home/
    
assignees:
  - remgi
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: remgi.github.io
  baseUrl: /uptimecic
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CIC Pages Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
